# Generated by Django 3.1.5 on 2021-01-30 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('name', models.TextField()),
                ('writer', models.CharField(max_length=60)),
                ('editor', models.CharField(max_length=60)),
                ('category', models.CharField(max_length=30)),
                ('image', models.ImageField(upload_to='images/')),
                ('story', models.TextField()),
                ('summary', models.CharField(max_length=700, null=True)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
    ]
