# Generated by Django 3.1.5 on 2021-02-05 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20210204_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='writer',
            name='num_ratings',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
